### PR TITLE
[#38] Fix styleId to use template literals

### LINKED ISSUE #38: StyleId is not used
The `styleId` parameter is not used as it is outside of a template string

### PR DESCRIPTION
**Pull request by sawyerclick**
styleId was previously built as "${styleId}" - rendering on the page as <style id='${styleId}"/>. I've replaced the double quotes with template literals so the actual id is passed through

closes #38

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -49,7 +49,7 @@ function injectionCSSCodePlugin(cssToInject: string, styleId: string | null): Pl
                 const cssCode = JSON.stringify(cssToInject.trim());
 
                 return `try{var elementStyle = document.createElement('style');${
-                    typeof styleId == 'string' && styleId.length > 0 ? 'elementStyle.id = "${styleId}";' : ''
+                    typeof styleId == 'string' && styleId.length > 0 ? 'elementStyle.id = `${styleId}`;' : ''
```
Comment (Marco-Prontera) [inline src/utils.ts:52]: Thank you for your contribution!
Can you change 'elementStyle.id = `${styleId}`;' to `elementStyle.id = ${styleId};` since it's more clear?

As soon as you have done the fix I will publish the new version

**Review by Marco-Prontera — CHANGES_REQUESTED** [review]
One little thing and we are ready! 🚀

**Review by Marco-Prontera — APPROVED** [review]
🚀

**Comment by Marco-Prontera** [comment]
@sawyerclick new version published https://www.npmjs.com/package/vite-plugin-css-injected-by-js/v/2.0.3 thank you for the contribution 😉
